### ISSUE TITLE
Codegen in a solution

### ISSUE THREAD

**Issue by aalmada** [unoplatform/Uno.SourceGeneration#116]
## I'm submitting a...
Sample app request

## Current behavior
I'm trying to setup code generation in one of my open-source projects. It contains a main project that is distributed as a NuGet package. I just want to generate code in the main project, using my own generator, before it's packaged.

## Expected behavior
I've read the [README](https://github.com/unoplatform/Uno.SourceGeneration/blob/master/readme.md#using-the-generator-inside-the-same-solution-another-project) and the source of [Uno.CodeGen](https://github.com/unoplatform/Uno.CodeGen/tree/master/src) multiple times and I still can't figure it out. The targets and the dependencies do not make sense to me.

Sorry to be asking this but honestly, I researched as much as I could...

## Environment

```
Nuget Package: 

Package Version(s): 
1.32.0

Affected platform(s):
- [ ] iOS
- [ ] Android
- [ ] WebAssembly
- [x] Windows
- [x] macOS
- [x] Build tasks

Visual Studio
- [x] 2019 (version: Enterprise 16.5.0 Preview 1.0)
- [x] Code (version: 1.41.0)
- [ ] 2017 Preview (version: )
- [ ] for Mac (version: )

Relevant plugins
- [ ] Resharper (version: )
```

**Comment by jeromelaban** [comment]
Hi @aalmada, if you don't intend to ship the generator alonside your package, you can use this sample: https://github.com/jeromelaban/inpc.generator

It shows how to create one inside the same solution.

**Comment by aalmada** [comment]
@jeromelaban It took me some time to fine tune the logic for my generator but it's finally working!
It's building on Linux, macOS and Windows.
https://github.com/NetFabric/NetFabric.Hyperlinq
Thanks you so much for the help and for this great project!...

**Comment by jeromelaban** [comment]
Glad I could help! 

You'll probably discover it later on large code bases, but if you use resolved `INamedTypeSymbol` instances instead of strings, you'll get better generation performance: 
https://github.com/NetFabric/NetFabric.Hyperlinq/blob/7f15d00e8d594b118d3409990e6429870f2c09fa/NetFabric.Hyperlinq.Generator/Extensions.cs#L112

**Comment by aalmada** [comment]
@jeromelaban Yes, I now need to refactor the code for performance. Any feedback is welcome. 

Looking at this method in particular, there's a lot that can be done.

I now noticed that I can reduce the number of enumerators by using an `Any` with the predicate.

[I use `GetTypeByMetadataName` to resolve the attributes](https://github.com/NetFabric/NetFabric.Hyperlinq/blob/master/NetFabric.Hyperlinq.Generator/Extensions.cs#L144) but that means I have to either pass the `Compilation` or each resolved `INamedSymbol` to many of my methods. I was trying to avoid that clutter...

How do you deal with that?
