### ISSUE TITLE
Project gets built using Visual Studio, but dotnet build results into an error

### ISSUE THREAD

**Issue by ysmoradi** [unoplatform/Uno.SourceGeneration#62]
## I'm submitting a...
- Bug report (I searched for similar issues and did not find one)  

## Current behavior
There is a sample project attached to this issue. I can build that project using visual studio, but when I run dotnet build in command line, I receive following error:

```uno.sourcegenerationtasks\1.28.0-dev.145\build\net45\Uno.SourceGenerationTasks.targets(100,4): error : Generation failed, error code -2147450740```

![image](https://user-images.githubusercontent.com/5352980/48214227-c4219400-e394-11e8-8537-197d6cd093cd.png)
[UnoSourceGenerationIssueRepo.zip](https://github.com/nventive/Uno.SourceGeneration/files/2562707/UnoSourceGenerationIssueRepo.zip)

## Expected behavior
Project gets build as like as Visual Studio's build.

## Minimal reproduction of the problem with instructions
Extract the repo and build that.

## Environment
```
Nuget Package: 1.28.0-dev.145

Affected platform(s):
- [X] Build tasks

Visual Studio
- [X] 2017 (version: 15.8.5)

DotNet Core SDK 2.1.402
```

You can also have a look at my source code generator's codes [here](https://github.com/bit-foundation/bit-framework/tree/master/BitTools/BitCodeGeneratorTask).

**Comment by jeromelaban** [comment]
Thanks for the report. I'm guessing this is somehow expected as the project you're building is net46, and dotnet build is using .NET Core. Why not using msbuild directly for this project ?

**Comment by ysmoradi** [comment]
Yeah, I completely understand what you mean.
But **dotnet ef migrations list** as an example runs **dotnet build** and **dotnet run** behind the scenes.
Note that **dotnet run** & **dotnet build** are capable to build full .net framework projects.

**Comment by jeromelaban** [comment]
Got it. This is not a scenario that was tested at all, so that may explain why this happens.

**Comment by ysmoradi** [comment]
Is it possible to do something for this? Thanks.

**Comment by jeromelaban** [comment]
The latest package fixes part of the issue. Being able to run in this context implies that the version of Roslyn used in generators does not use any of the Workspaces.Desktop components.

**Comment by dahlia** [comment]
I'm facing apparently the same issue (except an error code I got is 140 instead of -2147450740, though I guess the number depends on if it's on macOS or Windows) to this during restoring Uno.CodeGen package.  I am on macOS, and the package versions `dotnet restore` command installed are:

```
$ dotnet restore
  Restoring packages for /~/SampleApp/SampleApp.csproj...
  Installing Uno.Injectable 1.30.0-dev.102.
  Installing Uno.Immutables 1.30.0-dev.102.
  Installing Uno.CodeGen 1.30.0-dev.102.
```

When I run `dotnet build` it reports like below:

```
$ dotnet build
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

/~/SampleApp/SampleApp.csproj : warning NU1701: Package 'Uno.SourceGenerationTasks 1.29.0-dev.157' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
  Restore completed in 40.56 ms for /~/SampleApp/SampleApp.csproj.
/~/SampleApp/SampleApp.csproj : warning NU1701: Package 'Uno.SourceGenerationTasks 1.29.0-dev.157' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
Error:
  An assembly specified in the application dependencies manifest (Uno.SourceGeneration.Host.deps.json) was not found:
    package: 'ManagedEsent', version: '1.9.4'
    path: 'lib/net40/Esent.Interop.dll'
/~/.nuget/packages/uno.sourcegenerationtasks/1.29.0-dev.157/build/net45/Uno.SourceGenerationTasks.targets(100,4): error : Generation failed, error code 140 [/~/SampleApp/SampleApp.csproj]

Build FAILED.

/~/SampleApp/SampleApp.csproj : warning NU1701: Package 'Uno.SourceGenerationTasks 1.29.0-dev.157' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
/~/SampleApp/SampleApp.csproj : warning NU1701: Package 'Uno.SourceGenerationTasks 1.29.0-dev.157' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.
/~/.nuget/packages/uno.sourcegenerationtasks/1.29.0-dev.157/build/net45/Uno.SourceGenerationTasks.targets(100,4): error : Generation failed, error code 140 [/~/SampleApp/SampleApp.csproj]
    2 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.97
```

**Comment by jeromelaban** [comment]
@dahlia could you try with the latest Uno.SourceGenerationTasks package ? This should have been improved.

**Comment by dahlia** [comment]
@jeremienventive Still does not work, but the error message was changed!

```
$ dotnet build
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restore completed in 35.17 ms for ~/SampleApp/SampleApp.csproj.
Error:
  An assembly specified in the application dependencies manifest (Uno.SourceGeneration.Host.deps.json) was not found:
    package: 'System.Text.Encoding.CodePages', version: '4.3.0'
    path: 'runtimes/unix/lib/netstandard1.3/System.Text.Encoding.CodePages.dll'
~/.nuget/packages/uno.sourcegenerationtasks/1.29.0-dev.195/build/netstandard1.0/Uno.SourceGenerationTasks.targets(99,4): error : Generation failed, error code 140 [~/SampleApp/SampleApp.csproj]

Build FAILED.

~/.nuget/packages/uno.sourcegenerationtasks/1.29.0-dev.195/build/netstandard1.0/Uno.SourceGenerationTasks.targets(99,4): error : Generation failed, error code 140 [~/SampleApp/SampleApp.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:00.93
```

**Comment by jeromelaban** [comment]
@dahlia can you use `msbuild /r` instead? or are you forced to use `dotnet build` ?

**Comment by dahlia** [comment]
It seems reproducible by `dotnet build` command on Windows too.

**Comment by dahlia** [comment]
`<UnoSourceGeneratorUseGenerationHost>true</UnoSourceGeneratorUseGenerationHost>` workaround fixed the build using `msbuild /r` command.  Isn't a failure `dotnet build` made relevant to #81?

**Comment by jeromelaban** [comment]
It's probably another issue for macOS. Does it still not work with the workaround with `dotnet build` ?

**Comment by dahlia** [comment]
The workaround fixed `msbuild /r` on macOS, but still `dotnet build` does not work on both macOS and Windows.  FYI here's the source code to reproduce: <https://gist.github.com/dahlia/34595dc89c7382b09214043f6d01bc9e>.

**Comment by ysmoradi** [comment]
I'm experiencing the same issue with Uno.SourceGenerationTasks (1.29.0-dev.200)

**Comment by ysmoradi** [comment]
)-:

**Comment by ysmoradi** [comment]
> The latest package fixes part of the issue. Being able to run in this context implies that the version of Roslyn used in generators does not use any of the Workspaces.Desktop components.

Using 1.29.0-dev.237, there is a new error because of using AppDomain class:

```
.nuget\packages\uno.sourcegenerationtasks\1.29.0-dev.237\build\netstandard1.0\Uno.SourceGenerationTasks.targets(102,2): error : Could not load type 'System.AppDomainSetup' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
```

**Comment by jeromelaban** [comment]
Having that parameter would make sense indeed. I tried your original solution again, and I'm having this:
```
         ---begin host ERROR output---
         Error:
           An assembly specified in the application dependencies manifest (Uno.SourceGeneration.Host.deps.json) was not found:
             package: 'System.Security.Principal.Windows', version: '4.5.1'
             path: 'runtimes/win/lib/netcoreapp2.0/System.Security.Principal.Windows.dll'

         ---end host output---
```

Curiously, I'm not getting this with the netcoreapp sample in the SourceGeneration solution, there may be something in your generators that creates this issue. Do you depend on `System.Security.Principal.Windows.dll` explicitly ?

**Comment by ysmoradi** [comment]
Thanks for your attention.

[XCodeGeneratorTask.zip](https://github.com/nventive/Uno.SourceGeneration/files/2776880/XCodeGeneratorTask.zip)
Check out my sample. It has no special code at all! The error gets raised when "dotnet" commands such as "dotnet build" and "dotnet ef migrations list" results into an exception when the uno source generator tries to create a new app domain and dotnet sdk which is based on dotnet core has no support for AppDomain.

.nuget\packages\uno.sourcegenerationtasks\1.29.0-dev.237\build\netstandard1.0\Uno.SourceGenerationTasks.targets(102,2): error : Could not load type 'System.AppDomainSetup' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'

**Comment by jeromelaban** [comment]
I've made many changes in #94 and the CI is minimally validating a .NET Core CLI build, this should improve the state of this issue.

**Comment by dahlia** [comment]
I tried [Uno.CodeGen 1.30.0 and Uno.SourceGenerationTasks 1.29.0](https://gist.github.com/dahlia/34595dc89c7382b09214043f6d01bc9e/e9102c3b1571004e7b54e79b69e8a859b860c601).  It now gets built using Visual Studio IDE on Windows, but still fails to build with `dotnet build` command on macOS:

```bash
$ dotnet build
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for /.../SampleApp.csproj...
  Generating MSBuild file /.../obj/SampleApp.csproj.nuget.g.props.
  Generating MSBuild file /.../obj/SampleApp.csproj.nuget.g.targets.
  Restore completed in 272.34 ms for /.../SampleApp.csproj.
~/.nuget/packages/uno.sourcegenerationtasks/1.29.0/build/netstandard1.0/Uno.SourceGenerationTasks.targets(102,2): error : Could not load type 'System.AppDomainSetup' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. [/.../SampleApp.csproj]

Build FAILED.

~/.nuget/packages/uno.sourcegenerationtasks/1.29.0/build/netstandard1.0/Uno.SourceGenerationTasks.targets(102,2): error : Could not load type 'System.AppDomainSetup' from assembly 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'. [/.../SampleApp.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:01.40
```

I tried the bleeding edge versions as well: [Uno.CodeGen 1.31.0-dev.128 and Uno.SourceGenerationTasks 1.30.0-dev.268](https://gist.github.com/dahlia/34595dc89c7382b09214043f6d01bc9e/4f4b44f13b8677efc2ea821b0cafa2e5371d7a50).  It shows a different error:

```bash
$ dotnet build
Microsoft (R) Build Engine version 15.9.20+g88f5fadfbe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.

  Restoring packages for /.../SampleApp.csproj...
  Installing Uno.Immutables 1.31.0-dev.128.
  Installing Uno.Injectable 1.31.0-dev.128.
  Installing Uno.Equality 1.31.0-dev.128.
  Installing Uno.SourceGenerationTasks 1.30.0-dev.268.
  Installing Uno.CodeGen 1.31.0-dev.128.
  Generating MSBuild file /.../obj/SampleApp.csproj.nuget.g.props.
  Generating MSBuild file /.../obj/SampleApp.csproj.nuget.g.targets.
  Restore completed in 12.8 sec for /.../SampleApp.csproj.
Error:
  An assembly specified in the application dependencies manifest (Uno.SourceGeneration.Host.deps.json) was not found:
    package: 'System.Security.Principal.Windows', version: '4.5.1'
    path: 'runtimes/unix/lib/netcoreapp2.0/System.Security.Principal.Windows.dll'
~/.nuget/packages/uno.sourcegenerationtasks/1.30.0-dev.268/build/netstandard1.0/Uno.SourceGenerationTasks.targets(105,2): error : Generation failed, error code 140 [/.../SampleApp.csproj]

Build FAILED.

~/.nuget/packages/uno.sourcegenerationtasks/1.30.0-dev.268/build/netstandard1.0/Uno.SourceGenerationTasks.targets(105,2): error : Generation failed, error code 140 [/.../SampleApp.csproj]
    0 Warning(s)
    1 Error(s)

Time Elapsed 00:00:14.02
```

**Comment by kijun** [comment]
Any updates on this issue? :)

**Comment by dzmitry-lahoda** [comment]
Does not work via `dotnet build` on my Windows to. I could send a report, but seems this is not priority to support anything except Visual Studio on Windows.  I have `msbuild tools 2017`, `omnisharp`, `vscode`, `dotnet` core skd 2-3, .net full sdk 4.7.2, Windows 10.

**Comment by jeromelaban** [comment]
@aalmada  Can you try with the Source Generators 2.0 ? Use packages from this feed: https://pkgs.dev.azure.com/uno-platform/1dd81cbd-cb35-41de-a570-b0df3571a196/_packaging/unoplatformdev/nuget/v3/index.json 

This build is compatible with .NET Core 3.0 and this may help with this scenario.

**Comment by aalmada** [comment]
@jeromelaban Yes! It fixes the issue. It also does not require the `Microsoft.NETFramework.ReferenceAssemblies` package for .NET Core targets. Thanks!

**Comment by jeromelaban** [comment]
The support for .NET Core has improved significantly for .NET Core 3.1 in the Uno.SourceGenerators 2.x, and will enable support for .NET 5 Preview 6 and later in 3.0.
